name: Snapshot

on:
  push:
    branches:
      - "main"
      - "terrarium-card"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          commit_sha: ${{ github.sha }}
          custom_tag: snapshot
          default_bump: false
          default_prerelease_bump: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ""
