name: Snapshot

on:
  push:
    branches:
      - "main"
      - "terrarium-card"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-node@v4"
        with:
          node-version-file: ".tool-versions"
      - run: "yarn install --frozen-lockfile"

      - run: "yarn run build"

      - name: "Create release"
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release delete snapshot -y --cleanup-tag || true
          gh release create \
            snapshot \
            dist/card-collection.js \
            dist/card-collection.js.map \
            --prerelease \
            --title Snapshot
